export const FETCH_CONVERSATION_REQUEST = 'FETCH_CONVERSATION_REQUEST';
export const SAVE_CONVERSATION_REQUEST = 'SAVE_CONVERSATION_REQUEST';
export const UPDATE_CONVERSATION_REQUEST = 'UPDATE_CONVERSATION_REQUEST'
export const DELETE_CONVERSATION_REQUEST = 'UPDATE_CONVERSATION_REQUEST'
export const CONVERSATION_SUCCESS = 'CONVERSATION_SUCCESS';
export const CONVERSATION_FAILURE = 'CONVERSATION_FAILURE';

export const FETCH_CONVERSATIONS_REQUEST = 'FETCH_CONVERSATIONS_REQUEST';
export const CONVERSATIONS_SUCCESS = 'CONVERSATIONS_SUCCESS';
export const CONVERSATIONS_FAILURE = 'CONVERSATIONS_FAILURE';