export const FETCH_CONVERSATION_REQUEST = 'FETCH_CONVERSATION_REQUES';
export const SAVE_CONVERSATION_REQUEST = 'SAVE_CONVERSATION_REQUEST';
export const UPDATE_CONVERSATION_REQUEST = 'UPDATE_CONVERSATION_REQUEST'
export const DELETE_CONVERSATION_REQUEST = 'UPDATE_CONVERSATION_REQUEST'
export const CONVERSATION_SUCCESS = 'CONVERSATION_SUCCESS';
export const CONVERSATION_FAILURE = 'CONVERSATION_FAILURE';

export const FETCH_ANSWER_TYPE_REQUEST = 'FETCH_ANSWER_TYPE_REQUEST';
export const ANSWER_TYPE_SUCCESS = 'FETCH_ANSWER_TYPE_SUCCESS';
export const ANSWER_TYPE_FAILURE = 'FETCH_ANSWER_TYPE_FAILURE';